title: "TBMガイド"
summary: "TBM（Technology Business Management）は、ITコストを可視化し、その価値を最大化するための経営管理手法です。この書籍では、TBMの基本概念からその構造（標準分類法、コスト配賦モデル）、導入・運用のプロセス、そして具体的な活用方法までを体系的に解説します。"
topics: [
  "TBM",
  "ITコスト管理",
  "データ分析",
]
published: true
published_at: 2025-04-28
price: 0 # 有料の場合200〜5000
